Hometask 1
Katenkar23/smart-home-2019 pull request #1
Opened 2019-10-09 11:23 UTC by Katenkar23

Добрый день!

Сделал задание, как получилось. Прошу Вас посмотреть и написать свои комментарии, что ещё необходимо доделать.

Спасибо.

@sbt-agoshkov, @a-ivanov, не смог добавить Вас, как ревьюэров, поэтому указал здесь.

2019-10-10 15:26 UTC, iagoshkov requested changes
Переделайте по комментариям, пока незачет.

2019-10-10 15:26 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +
Цикл обработки событий - это отдельная responsibility.
Сейчас нарушается SRP.
Исправьте.

2019-10-10 15:26 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>              if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
Здесь сейчас нарушается OCP - каждый раз при добавлении нового события или нового обработчика нам придется менять существующий код.
Лучше код создания Handler-ов вынести в отдельной место (в "конфигурационный код").
А внутренность цикла переписать так, чтобы не было создания EventHandler-а на каждое событие.

2019-10-10 15:26 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/DoorSensorEventHandler.java
> +                        System.out.println("Door " + door.getId() + " in room " + room.getName() + " was closed.");
Здесь нарушен SRP - меняем состояние door  + выполняем сценарий умного дома.
Исправьте.

2019-10-10 15:26 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/JsonHomeExportProvider.java
> +public class JsonHomeExportProvider implements HomeExportProvider {
HomeExportProvider - плохое название. Provider предоставляет что-то. В случае с HomeStateProvider - он предоставлял состояние дома.
Тут же скорее или HomeExporter или HomeWriter.

2019-10-10 15:26 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/JsonHomeExportProvider.java
> +    public void Export() throws IOException {
методы camelCase

2019-10-10 15:26 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/LightSensorEventHandler.java
> +    public void AllLightOff() {
Этот метод никак не используется внутри этого класса. Зачем он здесь?
Он должен быть в другом классе. Подумайте в каком и перенесите.

2019-10-10 15:26 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SensorEventHandler.java
> +    void Handle();
camelCase

2019-10-10 15:26 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeStateProvider.java
> +    SmartHome getHomeState() throws IOException;
throws IOException в этом методе плохо, т.к. Provider-ы могут быть разные и тут у вас "протекает" деталь реализации (работа с файлами), а в случае Provider-а, который берет дом из базы данных - будет необходимость кидать Exception связанные с БД, какой-нибудь java.sql.Exception. Этого не должно быть в абстракции.

2019-10-14 15:20 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/JsonHomeExportProvider.java
> +    public void Export() throws IOException {
Исправлено.

2019-10-14 15:20 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/LightSensorEventHandler.java
> +    public void AllLightOff() {
Исправлено.

2019-10-14 15:20 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/SensorEventHandler.java
> +    void Handle();
Исправлено.

2019-10-14 15:20 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/SmartHomeStateProvider.java
> +    SmartHome getHomeState() throws IOException;
Исправлено.

2019-10-14 15:24 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/JsonHomeExportProvider.java
> +public class JsonHomeExportProvider implements HomeExportProvider {
Исправлено.

2019-10-22 08:56 UTC, a-ivanov requested changes

2019-10-22 08:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
Цикл **обработки** событий - это все еще отдельная responsibility.
Сейчас нарушается SRP.
Исправьте.

2019-10-22 08:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorSensorEventHandler.java
> +    public void handle(SensorEvent event) {
Обработка события "умного дома" - это отдельная responsibility. Исправьте.

2019-10-23 20:56 UTC, a-ivanov requested changes

2019-10-23 20:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorSensorEventHandler.java
> +    public void handle(SensorEvent event) {
Не исправлено

2019-10-23 20:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    public static void sendCommand(SensorCommand command) {
Это отдельная responsibility. Исправьте.

2019-10-23 20:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventController.java
> +    private static SensorEvent getNextSensorEvent() {
В этом классе смешаны responsibility: новые события и цикл обработки. Исправьте.

2019-10-23 20:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/JsonHomeWriter.java
> +            writer.write(jsonString);
Модификация через ссылку объекта вне скоупа функции - плохая практика написания кода, перенесите тогда уж file аргументом в export.

2019-10-23 20:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorSensorEventHandler.java
> +                            if (room.getName().equals("hall")) {
Вот тут - отдельная responsibility по обработке события "умного дома".

2019-10-23 20:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ScenarioController.java
> +    public void runCloseHallDoorScenario() {
Зачем нужен публичный метод, который вызывает другой публичный метод?

2019-10-26 17:31 UTC, a-ivanov requested changes
Не доделано по замечаниям в очередной раз.

2019-10-26 17:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventGenerator.java
> +public class EventGenerator {
Добавьте интерфейс.

2019-10-26 17:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorCommandController.java
> +                            if (room.getName().equals("hall")) {
Вы так и не исправили проблему с SRP - этот обработчик обрабатывает несколько разных событий с дверью. Без правки зачета нет. Посмотрите на свой ScenarioController.

2019-10-26 17:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    public static void sendCommand(SensorCommand command) {
Либо исправьте, либо удалите не используемый код.

2019-10-28 15:18 UTC, Katenkar23 commented
Вроде всё сделал по Вашим замечаниям. Прошу проверить.

2019-11-06 14:56 UTC, Katenkar23 commented
По согласованию с @a-ivanov закрываю этот пулл-реквест. Дальнейшие изменения буду делать в ветке hometask-2.

2019-11-06 14:56 UTC, closed without merging