Hometask 2
Katenkar23/smart-home-2019 pull request #3
Opened 2019-11-03 19:53 UTC by Katenkar23

Отправлял до этого пуллреквест, но он закрылся, когда я из-за ошибок ребэйза вынужден был удалить вторую ветку. Отправляю реквест ещё раз, вроде всё там реализовал, кроме тестов.
Прошу проверить, и дать свои комментарии.

2019-11-05 23:16 UTC, a-ivanov requested changes
2е дз не выполнено, перечитайте задание. Надо использовать внутренний итератор в `Actionable` во всех обработчиках.

2019-11-05 23:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Setup.java
> +    public void handle(SensorEvent event) {
Ну, очевидно, здесь не только настройки, но и бизнес-логика с циклом обработки. Разнесите конфигурацию отдельно.

2019-11-05 23:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/SensorCommand.java
> +            case LIGHT_ON : this.type = CommandType.LIGHT_ON;
Нарушение OCP, новые события - новое редактирование этого кода, исправьте.

2019-11-05 23:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/controllers/HomeCommandController.java
> +public interface HomeCommandController {
CommandSender?

2019-11-05 23:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/DoorIterator.java
> +public class DoorIterator implements Iterator<Door> {
Этого класса по заданию здесь быть не должно - мы используем внутренний итератор.

2019-11-05 23:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/Door.java
> +
Где имплементация? Что должна дверь делать, когда с ней выполняют `Action`?

2019-11-05 23:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/Light.java
> +
Где имплементация?

2019-11-05 23:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/LightIterator.java
> +public class LightIterator implements Iterator<Light> {
Удалите этот класс, это не по заданию, нужен внутренний итератор.

2019-11-05 23:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/Room.java
> +        for (Door door : getDoors()) {
Где выполнение действия над `Room`? Она тоже `Actionable`.

2019-11-05 23:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/SmartHome.java
> +        for (Room room : getRooms()) {
Где выполнение действия над `SmartHome`? Он тоже `Actionable`.

2019-11-06 15:10 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/Setup.java
> +    public void handle(SensorEvent event) {
Переделал, теперь класс Setup просто хранитель обработчиков событий

2019-11-06 15:19 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/event/SensorCommand.java
> +            case LIGHT_ON : this.type = CommandType.LIGHT_ON;
Убрал этот конструктор - неиспользуемый код.

2019-11-10 23:53 UTC, a-ivanov requested changes
По 2 - зачет, доделайте по комментарию - по 1 будет зачет. Потом смерджите эту ветку в мастер и синхронизируйте мастер с остальными рабочими ветками.

2019-11-10 23:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/handlers/EventHandler.java
> +        while (event != null) {
Это отдельная ответственность, не SensorEventHandler. Выделите в отдельный класс, там делайте new Setup(this.getSmartHome()).

2019-11-13 16:18 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/event/handlers/EventHandler.java
> +        while (event != null) {
Отрефакторил этот класс. Посмотрите, пожалуйста, чтобы я мог продолжить. И ещё вопрос, как синхронизировать мастер с остальными ветками?

2019-11-17 22:37 UTC, a-ivanov approved these changes

2019-11-17 22:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/handlers/EventHandler.java
> +        while (event != null) {
Этот пуллреквест - мерджите в мастер.
В командной строке заходите в директорию с проектом. git fetch origin. git checkout <ветка, куда надо синхронизировать правки>. git merge master.

2019-11-17 22:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/handlers/EventHandler.java
> +        while (event != null) {
https://www.atlassian.com/git/tutorials/using-branches/git-merge

2019-11-18 12:53 UTC, merged