Hometask 3
Katenkar23/smart-home-2019 pull request #4
Opened 2019-11-04 22:43 UTC by Katenkar23

2019-11-05 23:17 UTC, a-ivanov requested changes
Внесите правки по 1му и 2му дз.

2019-11-10 23:57 UTC, a-ivanov requested changes
Доправьте по 1 (см. в https://github.com/Katenkar23/smart-home-2019/pull/3), и домерджите сюда все свои поправки, чтобы тут были выполненные 1 и 2 дз.

2019-11-10 23:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/JsonSmartHomeStateProvider.java
> +            smartH = gson.fromJson(json, SmartHome.class);
А зачем сначала создавать пустой дом, а потом его переассайнивать на новый созданный из gson? Можно же просто объявить SmartHome smartH;

2019-11-10 23:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>      public static void main(String... args) throws IOException {
Еще кидает IOException?

2019-11-10 23:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Setup.java
> +        // припоявлении нового обработчика событий, необходимо добавить его сюда
А где декоратор для сигнализации? Он должен конфигурироваться на уровне EventHandler'ов.

2019-11-10 23:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/handlers/EventHandler.java
> +        while (event != null) {
Это отдельная ответственность, не SensorEventHandler. Выделите в отдельный класс, там делайте new Setup(this.getSmartHome()).

2019-11-10 23:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/AlarmSystemState.java
> +    void deactivate(int code);
По заданию тут еще метод по принудительному переводу в состояние тревоги (без кода).

2019-11-10 23:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/AlarmDeactivated.java
> +
Имплементация?

2019-11-10 23:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/AlarmAlert.java
> +public class AlarmAlert implements AlarmSystemState {
Имплементация?

2019-11-10 23:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/AlarmSystem.java
> +
Имплементация?

2019-11-10 23:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/AlarmActivated.java
> +public class AlarmActivated implements AlarmSystemState {
Имплементация?

2019-11-10 23:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/LightIterator.java
> +public class LightIterator implements Iterator<Light> {
Удалите ненужный класс.

2019-11-19 14:54 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/Application.java
>      public static void main(String... args) throws IOException {
Убрал.

2019-11-19 14:56 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/AlarmSystemState.java
> +    void deactivate(int code);
Сделано.

2019-11-19 14:56 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/AlarmDeactivated.java
> +
Сделано.

2019-11-19 14:57 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/AlarmAlert.java
> +public class AlarmAlert implements AlarmSystemState {
Сделано.

2019-11-19 14:57 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/AlarmSystem.java
> +
Сделано.

2019-11-19 14:57 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/smarthome/alarm/AlarmActivated.java
> +public class AlarmActivated implements AlarmSystemState {
Сделано.

2019-11-19 14:57 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/smarthome/LightIterator.java
> +public class LightIterator implements Iterator<Light> {
Убрал.

2019-11-19 14:59 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/smarthome/JsonSmartHomeStateProvider.java
> +            smartH = gson.fromJson(json, SmartHome.class);
Здесь я в тупике. Вообще слабое место.
Я не могу вынести исключение в метод, потому что он унаследован от интерфейса.
Поэтому использую try/catch, но если будет исключение, то вообще вернётся пустой дом((
Прошу помочь советом.

2019-11-19 15:00 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/event/handlers/EventHandler.java
> +        while (event != null) {
Сделано.

2019-11-19 16:31 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/Setup.java
> +        // припоявлении нового обработчика событий, необходимо добавить его сюда
вроде реализовал, прошу проверить

2019-11-25 08:42 UTC, a-ivanov requested changes

2019-11-25 08:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/JsonSmartHomeStateProvider.java
> +            smartH = gson.fromJson(json, SmartHome.class);
Если будет исключение, значит произошла ошибка при чтении состояния дома. Это нормально, значит, программа не может дальше работать. Можно отдать null и проверить в том месте, где этот метод вызывается и принять соответствующее решение.

2019-11-25 08:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/handlers/AlarmSystemDecorator.java
> +            delegate.handle(event);
Сейчас смс будет отправляться несколько раз при обработке одного и того же события - на каждом декораторе. Сделайте так, чтобы отправлялась только одна смс на одно событие в состоянии тревоги.

2019-11-26 14:47 UTC, Katenkar23 commented on src/main/java/ru/sbt/mipt/oop/event/handlers/AlarmSystemDecorator.java
> +            delegate.handle(event);
Написал метод, который шлёт смс для определённых событий. Теперь только одна смс отправляется на событие.

2019-11-29 11:34 UTC, a-ivanov requested changes

2019-11-29 11:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/handlers/AlarmSystemDecorator.java
> +            delegate.handle(event);
Ок, объясню по-другому:

```
for (SensorEventHandler handler : sensorHandlers) {
    handler.handle(event);
}
```

Приходит событие event, оно передается в каждый из обработчиков, которые настроены в Setup. Сейчас, если event.getType() == DOOR_OPEN || DOOR_CLOSED || ... все равно каждый обработчик из sensorHandlers отправит по 1 смс, т.е. всего sensorHandlers.length() смс. Нужно, чтобы была отправлена всего 1 смс на каждое приходящее event (если сигнализация включена).

В методе sendSMS внизу нарушен OCP, так делать нельзя. Новые типы событий тоже не забудете туда добавить?

И по заданию надо было, чтобы декоратор не только отправлял смс, но еще прекращал обработку событий (если сигнализация включена), у вас сейчас обработка продолжается.

2019-12-02 15:10 UTC, Katenkar23 commented
Антон, переделал декоратор, теперь он обернул сразу все обработчики событий. Надеюсь, на этот раз правильно сделал.
Спасибо.

2019-12-12 14:24 UTC, a-ivanov approved these changes

2019-12-25 16:06 UTC, closed without merging